package spinal.core.internals

import java.nio.charset.StandardCharsets
import java.nio.file.{Files, Path, Paths}
import morphhdl.{MorphNamedFieldVectors, MorphSignedCasts, MorphSignedDeclarations, MorphVerilog}
import morphhdl.frontend.HdlInt
import nativeapplication.BalancedNestedMechanismNativeOracle
import spinal.core._

/** Finite qualification inventory shared by two arithmetic profiles. All
  * independent field widths, inner counts and both branch values are explicit.
  * Results are generated by the hardware checker, never encoded in this list.
  */
object TypedBalancedReductionNestedMechanismArtifacts {
  val profiles = for (layout <- Vector("packed", "fields");
    signed <- Vector("legacy", "declarations", "casts")) yield layout -> signed
  val shapes = (for {
    (u, s, t, i, n) <- Vector((1, 1, 1, 1, 1), (3, 2, 4, 1, 1),
      (1, 4, 2, 3, 2), (4, 1, 3, 1, 3), (2, 3, 1, 2, 4),
      (3, 2, 4, 3, 5), (4, 4, 4, 3, 5), (2, 2, 2, 2, 5))
    mode <- 0 to 1
  } yield (u, s, t, i, n, mode)).toVector
  val parameterNames = Vector("U_W", "S_W", "TAG_W", "INNER", "COUNT", "MODE")
  def config(root: Path, module: String): SpinalConfig = {
    Files.createDirectories(root)
    val result = SpinalConfig(targetDirectory = root.toString,
      headerWithDate = false, bitVectorWidthMax = 65536)
    result.netlistFileName = module + ".v"
    result
  }
  /** Isolate native nested/widening publication from child binding diagnostics. */
  def directCandidate(root: Path, saturation: Boolean): Path = {
    val name = if (saturation) "NestedSaturationDirect" else "NestedMechanismDirect"
    MorphVerilog(config(root, name)) {
      new BalancedNestedMechanismChild(HdlInt.param("U_W", 3, 1, 4),
        HdlInt.param("S_W", 2, 1, 4), HdlInt.param("TAG_W", 4, 1, 4),
        HdlInt.param("INNER", 1, 1, 3), HdlInt.param("COUNT", 1, 1, 5),
        HdlInt.param("MODE", 0, 0, 1), saturation, name)
    }
    val result = root.resolve(name + ".v")
    require(Files.isRegularFile(result), "missing direct nested RTL: " + result)
    result
  }
  def candidate(root: Path, layout: String, signed: String, saturation: Boolean): Path = {
    require(profiles.contains(layout -> signed))
    val name = (if (saturation) "NestedSaturation" else "NestedMechanism") + "_" + layout + "_" + signed
    val base = config(root, name)
    val shaped = if (layout == "fields") MorphNamedFieldVectors.enable(base) else base
    val selected = signed match {
      case "legacy" => MorphSignedDeclarations.disable(MorphSignedCasts.disable(shaped))
      case "declarations" => MorphSignedDeclarations.enable(MorphSignedCasts.disable(shaped))
      case "casts" => MorphSignedCasts.enable(shaped)
    }
    MorphVerilog(selected) {
      new BalancedNestedMechanismTop(HdlInt.param("U_W", 3, 1, 4),
        HdlInt.param("S_W", 2, 1, 4), HdlInt.param("TAG_W", 4, 1, 4),
        HdlInt.param("INNER", 1, 1, 3), HdlInt.param("COUNT", 1, 1, 5),
        HdlInt.param("MODE", 0, 0, 1), saturation, name, name + "_Child")
    }
    val result = root.resolve(name + ".v")
    require(Files.isRegularFile(result), "missing generated nested matrix RTL: " + result)
    result
  }
  def emit(root: Path, saturation: Boolean): Unit = {
    Files.createDirectories(root)
    val candidates = profiles.map { case (layout, signed) =>
      val file = candidate(root.resolve("candidate"), layout, signed, saturation)
      val name = file.getFileName.toString.stripSuffix(".v")
      s"""{"layout":"$layout","signed_mode":"$signed","module":"$name","child_module":"${name}_Child","file":"candidate/$name.v"}"""
    }
    val cases = shapes.map { case (u, s, t, i, n, m) =>
      val id = s"u${u}_s${s}_t${t}_i${i}_n${n}_m$m"
      val name = "NativeNested_" + id
      SpinalVerilog(config(root.resolve("native"), name).copy(headerWithRepoHash = false)) {
        new BalancedNestedMechanismNativeOracle(u, s, t, i, n, m, saturation, name)
      }
      s"""{"id":"$id","uw":$u,"sw":$s,"tw":$t,"inner":$i,"count":$n,"mode":$m,"module":"$name","file":"native/$name.v"}"""
    }
    val scope = if (saturation) "59i-nested-saturation-widening" else "59i-nested-widening-capture-register-hierarchy"
    Files.write(root.resolve("manifest.json"),
      (s"""{"schema":1,"scope":"$scope","candidates":[${candidates.mkString(",")}],"cases":[${cases.mkString(",")}]}""" + "\n").getBytes(StandardCharsets.UTF_8))
  }
  def main(args: Array[String]): Unit = {
    require(args.length == 1, "usage: TypedBalancedReductionNestedMechanismArtifacts OUTPUT")
    emit(Paths.get(args(0)).toAbsolutePath.normalize(), saturation = false)
  }
}

object TypedBalancedReductionNestedSaturationWideningArtifacts {
  def main(args: Array[String]): Unit = {
    require(args.length == 1, "usage: TypedBalancedReductionNestedSaturationWideningArtifacts OUTPUT")
    TypedBalancedReductionNestedMechanismArtifacts.emit(
      Paths.get(args(0)).toAbsolutePath.normalize(), saturation = true)
  }
}
