package morphhdl

private[morphhdl] trait MorphSingleSourceVerilogReportProductElementName {
  def productElementName(index: Int): String
}

/** Preserve the field-name reflection generated by the historical case class. */
private[morphhdl] trait MorphSingleSourceVerilogReportProductNames
    extends MorphSingleSourceVerilogReportProductElementName { self: Product =>
  override def productElementName(index: Int): String = index match {
    case 0 => "toplevelName"
    case 1 => "generatedSourcesPaths"
    case 2 => "parameters"
    case 3 => "inheritedValidationPhaseIds"
    case _ => throw new IndexOutOfBoundsException(index.toString)
  }
}

private[morphhdl] object MorphSingleSourceVerilogReportProductNames {
  final val reportSerialVersionUID = 8748367316100203142L
  final val companionSerialVersionUID = -2414537719037776747L
}
