#!/usr/bin/env python3
"""Reproduce CDC-WIRE-01 native/registry records, then seal a committed source.

This is a maintainer utility, never an approval or CI bypass. Run `native` only
after committing the reviewed compiler/policy source. Commit its outputs, then
run `seal` and commit that seal. Every generated byte is subsequently checked by
the unchanged native and cumulative source verifiers; no source is generated or
changed by this utility.
"""
from __future__ import annotations
import argparse
import hashlib
import importlib.util
import json
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[2]
OUTER = 'morphhdl/scripts/check-increment-62-wa08-source-overlay.py'
CONTRACT = 'morphhdl/contracts/increment-62-wa08-source-overlay.json'
REGISTRY = 'morphhdl-passes/tests/formal_model/wire_assignment_ir/expected-signatures.json'


def git(*args: str) -> bytes:
    return subprocess.check_output(['git', '--literal-pathspecs', *args], cwd=ROOT)


def digest(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('phase', choices=('native', 'seal'))
    args = parser.parse_args()
    if args.phase == 'native':
        subprocess.run(['python3', 'morphhdl/scripts/check-native-source-preservation.py',
                        '--generate-template', 'morphhdl/contracts/increment-55-native-change-review.json',
                        '--output', 'morphhdl/contracts/native-source-preservation.json', '--force'],
                       cwd=ROOT, check=True)
        value = json.loads((ROOT/REGISTRY).read_bytes())
        for path in value['files']:
            value['files'][path] = digest((ROOT/path).read_bytes())
        (ROOT/REGISTRY).write_text(json.dumps(value, indent=2)+'\n')
        print('Native manifest and original formal signature path set refreshed; commit before seal.')
        return
    if git('status', '--porcelain', '--untracked-files=all').strip():
        raise SystemExit('Seal requires a clean committed source checkpoint.')
    spec = importlib.util.spec_from_file_location('cdc_wire_seal_outer', ROOT/OUTER)
    outer = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(outer)
    previous = json.loads((ROOT/CONTRACT).read_bytes())
    head = git('rev-parse', 'HEAD').decode().strip()
    paths = {e['path'] for e in previous['files']}
    changed = set(git('diff', '--no-renames', '--name-only', outer.BASE, head).decode().splitlines())
    paths |= {path for path in changed if outer.governed(path)}
    # Documentation describing the exact new scope is sealed too, even though
    # documentation has no compiler-source wildcard admission.
    paths |= {'docs/morphhdl/cdc-wire-fixed-point-source-review.md',
              'morphhdl/examples/contracts/symbolic_data_shapes.v'}
    paths -= {OUTER, CONTRACT}
    tree = outer.tree(ROOT, head)
    entries = []
    for path in sorted(paths):
        if path not in tree:
            raise SystemExit('Unexpected deleted source in cumulative seal: '+path)
        mode = tree[path][0]
        raw = outer.regular(ROOT, path, mode)
        if raw != git('show', head+':'+path):
            raise SystemExit('Worktree differs from immutable source: '+path)
        before = outer.frozen(ROOT, outer.BASE, path)
        entries.append({'path': path, 'mode': mode,
                        'before_sha256': digest(before) if before is not None else None,
                        'after_sha256': digest(raw)})
    value = {'schema_version': 1, 'base': outer.BASE, 'final_source_commit': head,
             'helper_normalized_sha256': digest(outer.normalized_helper((ROOT/OUTER).read_bytes())),
             'files': entries}
    serialized = (json.dumps(value, indent=2)+'\n').encode()
    (ROOT/CONTRACT).write_bytes(serialized)
    source = (ROOT/OUTER).read_text()
    source, replacements = re.subn(r'^CONTRACT_SHA256 = "[^"]+"$',
                                  'CONTRACT_SHA256 = "'+digest(serialized)+'"', source,
                                  count=1, flags=re.M)
    if replacements != 1:
        raise SystemExit('Missing unique cumulative manifest digest.')
    (ROOT/OUTER).write_text(source)
    print('Cumulative source seal anchored to '+head+'; commit seal before running source gates.')

if __name__ == '__main__':
    main()
