#!/usr/bin/env python3
"""Adversarial schema-2 target refresh tests in disposable Git repositories.

No production manifest is generated by these tests. The source checker must
retain schema-1 tests separately and accept only the pinned target in schema 2.
"""
from __future__ import annotations

import copy
import difflib
import importlib.util
import json
import os
from pathlib import Path
import re
import subprocess
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[2]
HELPER = "morphhdl/scripts/check-increment-59i-production-successor.py"
TEST = "morphhdl/scripts/test-increment-59i-production-successor.py"
CONTRACT = "morphhdl/contracts/increment-59i-production-successor.json"
SHARED = "core/src/main/Shared.scala"
TARGET_ONLY = "frontend/src/main/Target.scala"
FEATURE_ONLY = "core/src/main/Feature.scala"
TODO = "docs/morphhdl/parameterized-verilog-todo.md"
ANCHOR = "- [ ] **Increment 59i — Combined Vec/reduction compatibility, proof and publication closure**\n"


def git(root, *args, input=None):
    env = dict(os.environ, GIT_AUTHOR_NAME="Target refresh fixture", GIT_COMMITTER_NAME="Target refresh fixture",
        GIT_AUTHOR_EMAIL="fixture@example.invalid", GIT_COMMITTER_EMAIL="fixture@example.invalid")
    result = subprocess.run(["git", "-c", "core.hooksPath=/dev/null", *args], cwd=root, env=env,
        input=input, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=120)
    if result.returncode:
        raise RuntimeError(result.stderr.decode(errors="replace"))
    return result.stdout


def write(root, path, data):
    p = root / path
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_bytes(data)
    p.chmod(0o644)


def commit(root, label, parents=None):
    git(root, "add", "--all")
    tree = git(root, "write-tree").decode().strip()
    if parents is None:
        git(root, "commit", "-q", "-m", label)
        return git(root, "rev-parse", "HEAD").decode().strip()
    args = ["commit-tree", tree]
    for parent in parents:
        args += ["-p", parent]
    sha = git(root, *args, input=(label + "\n").encode()).decode().strip()
    git(root, "reset", "--hard", sha)
    return sha


def load(path):
    spec = importlib.util.spec_from_file_location("target_refresh_checker", path)
    module = importlib.util.module_from_spec(spec)
    exec(compile(path.read_bytes(), str(path), "exec"), module.__dict__)
    return module


def replace(raw, key, value):
    raw, count = re.subn((r'^' + key + r' = "[^"\n]+"$').encode(),
        (key + ' = "' + value + '"').encode(), raw, flags=re.M)
    if count != 1:
        raise AssertionError("ambiguous fixture constant " + key)
    return raw


def spans(path, before, after):
    a, b = before.decode(), after.decode()
    result = []
    for kind, i, j, k, l in difflib.SequenceMatcher(a=a, b=b, autojunk=False).get_opcodes():
        if kind != "equal":
            result.append({"id": path + ":" + str(len(result)), "reason": "Exact synthetic target reconciliation",
                "before_start": len(a[:i].encode()), "before_end": len(a[:j].encode()),
                "after_start": len(b[:k].encode()), "after_end": len(b[:l].encode()),
                "before": a[i:j], "after": b[k:l]})
    return result


class TargetRefreshTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory(prefix="59i-target-refresh-")
        self.addCleanup(self.tmp.cleanup)
        self.root = Path(self.tmp.name)
        git(self.root, "init", "-q")
        write(self.root, SHARED, b"common\n")
        write(self.root, TARGET_ONLY, b"old target\n")
        write(self.root, TODO, ("Fixture roadmap\n" + ANCHOR).encode())
        self.common = commit(self.root, "common base")
        write(self.root, SHARED, b"feature\n")
        write(self.root, FEATURE_ONLY, b"feature geometry\n")
        self.base = commit(self.root, "feature predecessor")
        git(self.root, "checkout", "--detach", self.common)
        write(self.root, SHARED, b"target\n")
        write(self.root, TARGET_ONLY, b"new target\n")
        self.target = commit(self.root, "target refresh")
        git(self.root, "checkout", "--detach", self.base)
        raw = (ROOT / HELPER).read_bytes()
        for key, value in (("BASE", self.base), ("INTEGRATION_TARGET", self.target),
                ("INTEGRATION_BASE", self.common), ("CONTRACT_SHA256", "UNSEALED")):
            raw = replace(raw, key, value)
        raw, count = re.subn(rb'^INTEGRATION_RECONCILIATIONS = frozenset\(\(.*?^\)\)$',
            ('INTEGRATION_RECONCILIATIONS = frozenset(("' + SHARED + '",))').encode(), raw, flags=re.M | re.S)
        self.assertEqual(count, 1)
        write(self.root, HELPER, raw)
        write(self.root, TEST, b"# Synthetic source inventory fixture\n")
        write(self.root, SHARED, b"feature + target\n")
        write(self.root, TARGET_ONLY, b"new target\n")
        self.source = commit(self.root, "reviewed joined source", [self.base, self.target])
        self.head, self.value = self.seal(self.source)
        self.checker = load(self.root / HELPER)
        self.checker.verify(self.root)

    def record(self, checker, before_ref, after_ref, path):
        before, after = checker.frozen(self.root, before_ref, path), checker.frozen(self.root, after_ref, path)
        return {"path": path,
            "before_mode": checker.tree(self.root, before_ref).get(path, (None,))[0],
            "after_mode": checker.tree(self.root, after_ref).get(path, (None,))[0],
            "before_sha256": None if before is None else checker.digest(before),
            "after_sha256": None if after is None else checker.digest(after),
            "reason": "Reviewed synthetic source union", "edits": spans(path, before or b"", after or b"")}

    def seal(self, source, transform=None):
        git(self.root, "reset", "--hard", source)
        c = load(self.root / HELPER)
        value = {"schema_version": 2, "predecessor": self.base,
            "predecessor_tree": git(self.root, "rev-parse", self.base + "^{tree}").decode().strip(),
            "source_commit": source, "source_tree": git(self.root, "rev-parse", source + "^{tree}").decode().strip(),
            "helper_normalized_sha256": c.digest(c.normalized_helper((self.root / HELPER).read_bytes())),
            "files": [self.record(c, self.base, source, path) for path in sorted(c.changed(self.root, self.base, source))],
            "target_integration": {"target_commit": self.target,
                "target_tree": git(self.root, "rev-parse", self.target + "^{tree}").decode().strip(),
                "common_base": self.common,
                "common_base_tree": git(self.root, "rev-parse", self.common + "^{tree}").decode().strip(),
                "files": [self.record(c, self.target, source, path) for path in sorted(c.changed(self.root, self.common, self.target))]}}
        if transform is not None:
            transform(value)
        raw = (json.dumps(value, indent=2, sort_keys=True) + "\n").encode()
        write(self.root, CONTRACT, raw)
        write(self.root, HELPER, replace((self.root / HELPER).read_bytes(), "CONTRACT_SHA256", c.digest(raw)))
        return commit(self.root, "seal joined source", [source]), value

    def reject(self, text):
        with self.assertRaisesRegex(RuntimeError, re.escape(text)):
            load(self.root / HELPER).verify(self.root)

    def variant(self, change=None, parents=None, manifest=None):
        git(self.root, "reset", "--hard", self.source)
        if change:
            change()
        source = commit(self.root, "variant joined source", parents or [self.base, self.target])
        self.seal(source, manifest)

    def test_exact_join_and_both_immutable_views(self):
        c = self.checker
        self.assertEqual(c.restore_source(self.root, SHARED, b"feature + target\n"), b"feature\n")
        self.assertEqual(c.target_source(self.root, SHARED, b"feature + target\n"), b"target\n")
        self.assertEqual(c.target_source(self.root, FEATURE_ONLY, b"feature geometry\n"), b"")
        self.assertEqual(c.target_source(self.root, TARGET_ONLY, b"new target\n"), b"new target\n")
        current = c.changed(self.root, self.common, "HEAD")
        self.assertEqual(c.target_inventory(self.root, current, self.common, full=True),
            c.changed(self.root, self.common, self.target))

    def test_normal_target_first_github_merge_and_checkbox_descendant(self):
        tree = git(self.root, "rev-parse", self.head + "^{tree}").decode().strip()
        merged = git(self.root, "commit-tree", tree, "-p", self.target, "-p", self.head,
            input=b"ordinary integration merge\n").decode().strip()
        git(self.root, "reset", "--hard", merged)
        self.checker.verify(self.root)
        write(self.root, TODO, (self.root / TODO).read_bytes().replace(b"[ ]", b"[x]", 1))
        commit(self.root, "fixture completion documentation")
        self.checker.verify(self.root)

    def test_schema_one_cannot_launder_two_parent_source(self):
        def mutate(value):
            value["schema_version"] = 1
            value.pop("target_integration")
        self.variant(manifest=mutate)
        self.reject("source must be one direct child of the immutable predecessor")

    def test_direct_source_cannot_claim_target_refresh(self):
        self.variant(parents=[self.base])
        self.reject("source must join the exact predecessor and reviewed target in order")

    def test_reversed_source_parents_rejected(self):
        self.variant(parents=[self.target, self.base])
        self.reject("source must join the exact predecessor and reviewed target in order")

    def test_extra_source_parent_rejected(self):
        git(self.root, "reset", "--hard", self.common)
        write(self.root, "extra.txt", b"unauthorized parent\n")
        other = commit(self.root, "third parent")
        self.variant(parents=[self.base, self.target, other])
        self.reject("source must join the exact predecessor and reviewed target in order")

    def test_target_only_dropped_change_rejected_even_after_resealing(self):
        self.variant(change=lambda: write(self.root, TARGET_ONLY, b"old target\n"))
        self.reject("unreviewed target-only change: " + TARGET_ONLY)

    def test_missing_target_inventory_entry_rejected(self):
        self.variant(manifest=lambda v: v["target_integration"]["files"].pop())
        self.reject("complete target integration inventory changed")

    def test_wrong_target_anchor_and_tree_rejected(self):
        value = copy.deepcopy(self.value)
        value["target_integration"]["target_commit"] = self.base
        with self.assertRaisesRegex(RuntimeError, "target integration anchors changed"):
            self.checker.validate_contract(value)
        self.variant(manifest=lambda v: v["target_integration"].update(target_tree="0" * 40))
        self.reject("immutable target integration tree changed: target")

    def test_wrong_common_base_tree_rejected(self):
        self.variant(manifest=lambda v: v["target_integration"].update(common_base_tree="0" * 40))
        self.reject("immutable target integration tree changed: common_base")

    def test_reconciliation_span_corruption_rejected(self):
        def mutate(value):
            edit = value["target_integration"]["files"][0]["edits"][0]
            edit["after"] = "X" * len(edit["after"])
        self.variant(manifest=mutate)
        self.reject("after span differs:")

    def test_uncommitted_and_staged_bytes_cannot_enter_target_projection(self):
        write(self.root, SHARED, b"unreviewed\n")
        with self.assertRaisesRegex(RuntimeError, "unreviewed bytes cannot enter target refresh projection"):
            self.checker.target_source(self.root, SHARED, b"unreviewed\n")
        self.reject("HEAD/index/worktree identity differs: " + SHARED)
        git(self.root, "add", SHARED)
        write(self.root, SHARED, b"feature + target\n")
        self.reject("HEAD/index identity differs")

    def test_newer_unreviewed_target_cannot_be_merged(self):
        git(self.root, "reset", "--hard", self.target)
        write(self.root, "later.txt", b"new target change\n")
        newer = commit(self.root, "unreviewed newer target")
        tree = git(self.root, "rev-parse", self.head + "^{tree}").decode().strip()
        merged = git(self.root, "commit-tree", tree, "-p", newer, "-p", self.head,
            input=b"unreviewed target merge\n").decode().strip()
        git(self.root, "reset", "--hard", merged)
        self.reject("integration target is not an ancestor of the reviewed target refresh")

    def test_merge_cannot_change_reviewed_source(self):
        write(self.root, SHARED, b"merge modified source\n")
        commit(self.root, "altered final merge", [self.target, self.head])
        self.reject("integration merge changed the reviewed feature tree")

    def test_target_projection_rejects_extra_and_forged_sources(self):
        with self.assertRaisesRegex(RuntimeError, "unreviewed bytes cannot enter target refresh projection"):
            self.checker.target_source(self.root, "core/src/main/Extra.scala", b"extra\n")
        with self.assertRaisesRegex(RuntimeError, "unreviewed bytes cannot enter target refresh projection"):
            self.checker.target_source(self.root, TARGET_ONLY, b"old target\n")

    def test_schema_and_span_boundary_controls(self):
        for field, replacement in (("files", []), ("common_base", "0" * 40)):
            value = copy.deepcopy(self.value)
            value["target_integration"][field] = replacement
            with self.assertRaises(RuntimeError):
                self.checker.validate_contract(value)
        value = copy.deepcopy(self.value)
        value["target_integration"]["files"][0]["edits"][0]["before_start"] = True
        with self.assertRaisesRegex(RuntimeError, "invalid target byte offset"):
            self.checker.validate_contract(value)


if __name__ == "__main__":
    unittest.main(verbosity=2)
